### ISSUE TITLE
Aimbot doesn't seem to recognize and shoot properly.

### ISSUE THREAD

**Issue by ashwinpathak** [sstokic-tgm/XxharCs-CS-1.6-MultiHack#1]
Unfortunately, whenever you switch ON the aimbot and try to shoot, it moves your crosshair from opponents head to teammate head. Please look in to this problem. Thanks.

**Comment by sstokic-tgm** [comment]
Hello, I'm aware of this. The aimbot which is coded in openGL is only a DM only aimbot. The other one which uses the engine functions(which has it's own class and files) checks the team and only targets the oponent players.
You can choose the aimbot you want here. Though for the one aimbot which uses the engine, you need a bit to update it correctly handlers.cpp to work correctly

**Comment by ashwinpathak** [comment]
Any future plans to have a no recoil (no spread) feature which can be used without Aimbot?

**Comment by sstokic-tgm** [comment]
No Recoil and No Spread is aimbot independet. If you take a look at https://github.com/sstokic-tgm/XxharCs-CS-1.6-MultiHack/blob/master/XxharCs%20CS%201.6%20MultiHack/handlers.cpp#L425
You can see it. Just add a cvar for no recoil and check it then there(for on/off)

**Comment by ashwinpathak** [comment]
Ohh alright...one more request, can you please make a 'build' folder and have the latest build there? Thanks

**Comment by sstokic-tgm** [comment]
In the Release folder(which can be found in the root directory) you can find the compiled build. =>
https://github.com/sstokic-tgm/XxharCs-CS-1.6-MultiHack/tree/master/Release

I added also the source and a compiled build for the CS 1.6 Protocol Version 48 (aka. Build 6153).
You can find it in the "build6153" branch.
