### ISSUE TITLE
Where is the src file for the .exe

### ISSUE THREAD

**Issue by JitCompiler** [sstokic-tgm/XxharCs-CS-1.6-MultiHack#4]
Tried compiling the code, but where is the main function for compiling into the exe?
A global search reveals that there is only a DllMain() in main.cpp, which I know should be the one for the .dll. 
Where is the src code for the exe?
Also sprites.cpp does a #include "..\console.h", but there is no console.h in the distribution, is it a system file i'm not aware of ?
Can't read the distributed project file since I'm using VC++2010

**Comment by sstokic-tgm** [comment]
There is no exe since there is no injector, its only the hack which is interal so its compiled to .dll.

Uh i see that now, it's not a system file, I guess you can ignore it.

**Comment by JitCompiler** [comment]
I mean there're 2 files for download. 1 XxharCs.exe and 1 harCs.dll, where is the exe from? I should compile it from the src, right? Is it a console app or win32 app?

**Comment by sstokic-tgm** [comment]
XxharCs.exe is just an injector and as I said there is no injector source here.
Write your own or use another one
